package io.modular.framework.tools;

import java.io.*;
import java.nio.file.*;
import java.util.jar.*;
import java.util.zip.ZipEntry;

/**
 * 模块打包工具
 * 将模块目录打包为JAR文件，自动生成module.properties
 */
public class ModulePackager {
    
    /**
     * 打包模块
     * 
     * @param sourceDir 模块源代码目录
     * @param outputJar 输出JAR文件路径
     * @param moduleName 模块名称
     * @param version 模块版本
     * @param dependencies 依赖声明（逗号分隔）
     * @throws IOException 如果打包失败
     */
    public static void packageModule(Path sourceDir, Path outputJar, 
                                    String moduleName, String version, 
                                    String dependencies) throws IOException {
        
        if (!Files.exists(sourceDir)) {
            throw new IOException("Source directory not found: " + sourceDir);
        }
        
        // 创建输出目录
        Files.createDirectories(outputJar.getParent());
        
        // 创建JAR文件
        try (JarOutputStream jos = new JarOutputStream(
                new FileOutputStream(outputJar.toFile()))) {
            
            // 添加META-INF/module.properties
            addModuleProperties(jos, moduleName, version, dependencies);
            
            // 添加类文件
            addClassFiles(jos, sourceDir, sourceDir);
            
            // 添加资源文件
            addResourceFiles(jos, sourceDir, sourceDir);
        }
        
        System.out.println("Module packaged: " + outputJar);
        System.out.println("  Module: " + moduleName + " v" + version);
        if (dependencies != null && !dependencies.trim().isEmpty()) {
            System.out.println("  Dependencies: " + dependencies);
        }
    }
    
    /**
     * 添加模块属性文件
     */
    private static void addModuleProperties(JarOutputStream jos, 
                                           String moduleName, String version,
                                           String dependencies) throws IOException {
        JarEntry entry = new JarEntry("META-INF/module.properties");
        jos.putNextEntry(entry);
        
        Properties props = new Properties();
        props.setProperty("module.name", moduleName);
        props.setProperty("module.version", version);
        
        if (dependencies != null && !dependencies.trim().isEmpty()) {
            props.setProperty("module.dependencies", dependencies);
        }
        
        props.setProperty("module.description", "Generated by ModulePackager");
        
        ByteArrayOutputStream baos = new ByteArrayOutputStream();
        props.store(baos, "Module properties");
        
        jos.write(baos.toByteArray());
        jos.closeEntry();
    }
    
    /**
     * 添加类文件
     */
    private static void addClassFiles(JarOutputStream jos, Path rootDir, Path currentDir) 
            throws IOException {
        
        try (DirectoryStream<Path> stream = Files.newDirectoryStream(currentDir)) {
            for (Path file : stream) {
                if (Files.isDirectory(file)) {
                    addClassFiles(jos, rootDir, file);
                } else if (file.toString().endsWith(".class")) {
                    addFileToJar(jos, rootDir, file);
                }
            }
        }
    }
    
    /**
     * 添加资源文件
     */
    private static void addResourceFiles(JarOutputStream jos, Path rootDir, Path currentDir) 
            throws IOException {
        
        try (DirectoryStream<Path> stream = Files.newDirectoryStream(currentDir)) {
            for (Path file : stream) {
                if (Files.isDirectory(file)) {
                    // 跳过META-INF目录（已经处理）
                    if (!file.getFileName().toString().equals("META-INF")) {
                        addResourceFiles(jos, rootDir, file);
                    }
                } else if (!file.toString().endsWith(".class")) {
                    // 非类文件作为资源添加
                    addFileToJar(jos, rootDir, file);
                }
            }
        }
    }
    
    /**
     * 添加文件到JAR
     */
    private static void addFileToJar(JarOutputStream jos, Path rootDir, Path file) 
            throws IOException {
        
        // 计算JAR内的相对路径
        String relativePath = rootDir.relativize(file).toString()
                .replace(File.separatorChar, '/');
        
        JarEntry entry = new JarEntry(relativePath);
        jos.putNextEntry(entry);
        
        // 写入文件内容
        Files.copy(file, jos);
        jos.closeEntry();
    }
    
    /**
     * 命令行接口
     */
    public static void main(String[] args) {
        if (args.length < 3) {
            System.err.println("Usage: ModulePackager <source-dir> <output-jar> <module-name> [version] [dependencies]");
            System.err.println("Example: ModulePackager ./target/classes ./my-module.jar com.example.module 1.0.0 \"core:[1.0,2.0),util:1.5.0\"");
            System.exit(1);
        }
        
        try {
            Path sourceDir = Paths.get(args[0]);
            Path outputJar = Paths.get(args[1]);
            String moduleName = args[2];
            String version = args.length > 3 ? args[3] : "1.0.0";
            String dependencies = args.length > 4 ? args[4] : "";
            
            packageModule(sourceDir, outputJar, moduleName, version, dependencies);
            
        } catch (Exception e) {
            System.err.println("Packaging failed: " + e.getMessage());
            e.printStackTrace();
            System.exit(1);
        }
    }
}